import type { Metadata } from "next";
import { Geist, Roboto_Slab } from "next/font/google";
import "./globals.css";
import "azure-maps-control/dist/atlas.min.css";

const geistSans = Roboto_Slab({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Roboto_Slab({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>{children}</body>
    </html>
  );
}
